use crate::sqlz::{
    Column, ConstraintType, ForeignKeyAction, GenericType, MigrationPlan, Provider, SqlzError,
    SqlzResult, Table,
};
use super::queries;
use super::constants;
use postgres::{Client, NoTls};
use std::collections::HashMap;
use std::rc::Rc;

pub struct PostgresqlProvider {
    client: Client,
}

impl PostgresqlProvider {
    pub fn new() -> SqlzResult<impl Provider> {
        Ok(PostgresqlProvider {
            client: Client::connect(
                "host=localhost user=postgres password=111 dbname=dvdrental",
                NoTls,
            )
            .map_err(|e| SqlzError::ConnectionError(e.to_string()))?,
        })
    }
}

impl Provider for PostgresqlProvider {
    fn get_tables(&mut self) -> SqlzResult<Vec<Table>> {
        let rows = self
            .client
            .query(queries::SELECT_TABLES, &[])
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        // 1. Initialize tables and columns
        let mut tables: Vec<Table> = rows
            .into_iter()
            .map(|row| read_table(&mut self.client, row.get("table_name")))
            .collect::<SqlzResult<_>>()?;

        // 2. Build a flat lookup map for columns to avoid O(N^2) searches and borrowing issues
        // Mapping: (table_name, column_name) -> Rc<Column>
        let column_lookup: HashMap<(String, String), Rc<Column>> = tables
            .iter()
            .flat_map(|t| {
                t.columns
                    .iter()
                    .map(|c| ((t.name.clone(), c.name.clone()), Rc::clone(c)))
            })
            .collect();

        // 3. Fill constraints and foreign keys using the lookup map
        for table in tables.iter_mut() {
            fill_constraints(&mut self.client, table)?;
            fill_foreign_keys(&mut self.client, table, &column_lookup)?;
        }

        Ok(tables)
    }

    fn tables_exists(&mut self, tables: &[Table]) -> SqlzResult<Vec<String>> {
        let mut result = Vec::with_capacity(tables.len());
        let table_names: Vec<&str> = tables.iter().map(|t| t.name.as_str()).collect();

        let rows = self
            .client
            .query(queries::SELECT_TABLES_EXISTS, &[&table_names])
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        rows.iter().for_each(|row| result.push(row.get("table_name")));

        Ok(result)
    }

    fn generate_schema(&mut self, plan: &MigrationPlan) -> SqlzResult<()> {
        if !plan.is_valid() {
            return Err(SqlzError::MappingError(format!(
                "Invalid migration plan for table '{}'",
                plan.table.name
            )));
        }

        let mut sql = format!("CREATE TABLE public.{} (\n", plan.table.name);
        let mut column_defs = Vec::new();

        for col in &plan.table.columns {
            let type_str = plan.target_column_type_map.get(&col.name).unwrap();
            let mut def = format!("    {} {}", col.name, type_str);

            if let GenericType::Decimal { .. } = col.col_type {
                let precision = col.numeric_precision.unwrap();
                let scale = col.numeric_scale.unwrap();
                def.push_str(&format!("({},{})", precision, scale));
            } else if let Some(max_len) = col.max_length {
                def.push_str(&format!("({})", max_len));
            }

            if col.is_identity {
                def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
            }

            if !col.is_nullable {
                def.push_str(" NOT NULL");
            }

            // TODO: Set default value

            column_defs.push(def);
        }

        sql.push_str(&column_defs.join(",\n"));
        sql.push_str("\n);");

        self.client
            .batch_execute(&sql)
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        Ok(())
    }

    fn migrate_data(&mut self, _plan: &MigrationPlan) -> SqlzResult<()> {
        todo!()
    }

    fn create_constraints(&mut self, _plan: &MigrationPlan) -> SqlzResult<()> {
        todo!()
    }
}

fn read_table(client: &mut Client, table_name: String) -> SqlzResult<Table> {
    let mut table = Table {
        name: table_name,
        columns: Vec::new(),
        constraints: Vec::new(),
    };

    let column_rows = client
        .query(queries::SELECT_COLUMNS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in column_rows {
        let data_type: String = row.get("data_type");
        let udt_name: String = row.get("udt_name");
        let char_len: Option<i32> = row.get("character_maximum_length");
        let mut numeric_precision: Option<i32> = row.get("numeric_precision");
        let mut numeric_scale: Option<i32> = row.get("numeric_scale");

        let col_type = map_native_type_to_sqlz(
            &data_type,
            &udt_name,
            char_len,
            numeric_precision,
            numeric_scale,
        );

        if !constants::PRECISION_TYPES.contains(&udt_name.as_str()) {
            numeric_precision = None;
            numeric_scale = None;
        }

        table.columns.push(Rc::new(Column {
            name: row.get("column_name"),
            is_nullable: row.get::<_, String>("is_nullable") == "YES",
            col_type,
            native_type: udt_name,
            is_identity: row.get::<_, String>("is_identity") == "YES",
            max_length: char_len,
            numeric_precision,
            numeric_scale,
        }));
    }

    Ok(table)
}

fn fill_constraints(client: &mut Client, table: &mut Table) -> SqlzResult<()> {
    let rows = client
        .query(queries::SELECT_CONSTRAINTS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in rows {
        let constraint_name: String = row.get("constraint_name");
        let constraint_type: String = row.get("constraint_type");
        let column_name: String = row.get("column_name");

        let column = table
            .columns
            .iter()
            .find(|c| c.name == column_name)
            .cloned();

        if let Some(col) = column {
            match constraint_type.as_str() {
                constants::CONSTRAINT_PK => {
                    // Check if we already have this PK (for multi-column PKs)
                    if let Some(ConstraintType::PrimaryKey { columns, .. }) = table
                        .constraints
                        .iter_mut()
                        .find(|c| matches!(c, ConstraintType::PrimaryKey { .. }))
                    {
                        columns.push(col);
                    } else {
                        table.constraints.push(ConstraintType::PrimaryKey {
                            constraint_name,
                            columns: vec![col],
                        });
                    }
                }
                constants::CONSTRAINT_UNIQUE => {
                    // Group unique constraints by name
                    if let Some(ConstraintType::Unique { columns, .. }) =
                        table.constraints.iter_mut().find(|c| match c {
                            ConstraintType::Unique {
                                constraint_name: n, ..
                            } => n == &constraint_name,
                            _ => false,
                        })
                    {
                        columns.push(col);
                    } else {
                        table.constraints.push(ConstraintType::Unique {
                            constraint_name,
                            columns: vec![col],
                        });
                    }
                }
                _ => {}
            }
        }
    }

    Ok(())
}

fn fill_foreign_keys(
    client: &mut Client,
    table: &mut Table,
    column_lookup: &HashMap<(String, String), Rc<Column>>,
) -> SqlzResult<()> {
    let rows = client
        .query(queries::SELECT_FOREIGN_KEYS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in rows {
        let column_name: String = row.get("column_name");
        let foreign_table: String = row.get("foreign_table_name");
        let foreign_column: String = row.get("foreign_column_name");

        let source = table.columns.iter().find(|c| c.name == column_name);
        let target = column_lookup.get(&(foreign_table.clone(), foreign_column));

        if let (Some(src_col), Some(ref_col)) = (source, target) {
            table.constraints.push(ConstraintType::ForeignKey {
                constraint_name: row.get("constraint_name"),
                source_column: Rc::clone(src_col),
                referenced_table: foreign_table,
                referenced_column: Rc::clone(ref_col),
                on_update: map_fk_action(&row.get::<_, String>("on_update")),
                on_delete: map_fk_action(&row.get::<_, String>("on_delete")),
            });
        }
    }

    Ok(())
}

fn map_fk_action(action: &str) -> ForeignKeyAction {
    match action {
        constants::FK_ACTION_CASCADE => ForeignKeyAction::Cascade,
        constants::FK_ACTION_SET_NULL => ForeignKeyAction::SetNull,
        constants::FK_ACTION_SET_DEFAULT => ForeignKeyAction::SetDefault,
        constants::FK_ACTION_RESTRICT => ForeignKeyAction::Restrict,
        _ => ForeignKeyAction::NoAction,
    }
}

pub fn map_native_type_to_sqlz(
    _data_type: &str,
    native_type: &str,
    char_len: Option<i32>,
    precision: Option<i32>,
    scale: Option<i32>,
) -> GenericType {
    match native_type {
        // Integers
        constants::NATIVE_TYPE_INT => GenericType::TinyInt,
        constants::NATIVE_TYPE_INT2 => GenericType::SmallInt,
        constants::NATIVE_TYPE_INT4 => GenericType::Integer,
        constants::NATIVE_TYPE_INT8 => GenericType::BigInt,

        // Floats
        constants::NATIVE_TYPE_FLOAT4 => GenericType::Float,
        constants::NATIVE_TYPE_FLOAT8 => GenericType::Double,
        constants::NATIVE_TYPE_NUMERIC | constants::NATIVE_TYPE_DECIMAL => GenericType::Decimal {
            precision: precision.unwrap() as usize,
            scale: scale.unwrap() as usize,
        },

        // Strings/Chars
        constants::NATIVE_TYPE_VARCHAR => GenericType::VarChar(char_len.unwrap_or(0) as usize),
        constants::NATIVE_TYPE_BPCHAR => GenericType::Char(char_len.unwrap_or(0) as usize), // "Blank-padded char"
        constants::NATIVE_TYPE_TEXT | constants::NATIVE_TYPE_NAME => GenericType::Text,

        constants::NATIVE_TYPE_BYTEA => GenericType::Blob(0),

        // Booleans
        constants::NATIVE_TYPE_BOOL => GenericType::Boolean,

        // Date/Time
        constants::NATIVE_TYPE_DATE => GenericType::Date,
        constants::NATIVE_TYPE_TIMESTAMP | constants::NATIVE_TYPE_TIMESTAMPTZ => {
            GenericType::Timestamp
        }

        // Fallback for custom types
        _ => GenericType::UserDefined(native_type.to_string()),
    }
}

pub fn map_sqlz_to_native_type(generic_type: &GenericType) -> String {
    match generic_type {
        GenericType::TinyInt => constants::NATIVE_TYPE_INT.to_string(),
        GenericType::SmallInt => constants::NATIVE_TYPE_INT2.to_string(),
        GenericType::Integer => constants::NATIVE_TYPE_INT4.to_string(),
        GenericType::BigInt => constants::NATIVE_TYPE_INT8.to_string(),

        GenericType::Float => constants::NATIVE_TYPE_FLOAT4.to_string(),
        GenericType::Double => constants::NATIVE_TYPE_FLOAT8.to_string(),
        GenericType::Decimal { .. } => constants::NATIVE_TYPE_NUMERIC.to_string(),

        GenericType::VarChar(_) => constants::NATIVE_TYPE_VARCHAR.to_string(),
        GenericType::Char(_) => constants::NATIVE_TYPE_BPCHAR.to_string(),
        GenericType::Text => constants::NATIVE_TYPE_TEXT.to_string(),

        GenericType::Blob(_) => constants::NATIVE_TYPE_BYTEA.to_string(),

        GenericType::Boolean => constants::NATIVE_TYPE_BOOL.to_string(),

        GenericType::Date => constants::NATIVE_TYPE_DATE.to_string(),
        GenericType::Timestamp => constants::NATIVE_TYPE_TIMESTAMP.to_string(),

        GenericType::UserDefined(_) => "text".to_string(),
    }
}
