use super::constants;
use super::{helper, queries};
use crate::sqlz::{
    BatchQueryResult, Column, ConstraintType, GenericType, MigrationPlan, PrimaryKeyConstraint,
    Provider, RowReadOptions, SqlzError, SqlzResult, Table,
};
use postgres::{Client, NoTls};
use std::collections::HashMap;
use std::rc::Rc;

pub struct PostgresqlProvider {
    client: Client,
}

impl PostgresqlProvider {
    pub fn new() -> SqlzResult<impl Provider<postgres::Row>> {
        Ok(PostgresqlProvider {
            client: Client::connect(
                "host=localhost user=postgres password=111 dbname=dvdrental",
                NoTls,
            )
            .map_err(|e| SqlzError::ConnectionError(e.to_string()))?,
        })
    }
}

impl Provider<postgres::Row> for PostgresqlProvider {
    fn get_tables(&mut self) -> SqlzResult<Vec<Table>> {
        let rows = self
            .client
            .query(queries::SELECT_TABLES, &[])
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        // 1. Initialize tables and columns
        let mut tables: Vec<Table> = rows
            .into_iter()
            .map(|row| read_table(&mut self.client, row.get("table_name")))
            .collect::<SqlzResult<_>>()?;

        // 2. Build a flat lookup map for columns to avoid O(N^2) searches and borrowing issues
        // Mapping: (table_name, column_name) -> Rc<Column>
        let column_lookup: HashMap<(String, String), Rc<Column>> = tables
            .iter()
            .flat_map(|t| {
                t.columns
                    .iter()
                    .map(|c| ((t.name.clone(), c.name.clone()), Rc::clone(c)))
            })
            .collect();

        // 3. Fill constraints and foreign keys using the lookup map
        for table in tables.iter_mut() {
            fill_constraints(&mut self.client, table)?;
            fill_foreign_keys(&mut self.client, table, &column_lookup)?;
        }

        Ok(tables)
    }

    fn tables_exists(&mut self, tables: &[Table]) -> SqlzResult<Vec<String>> {
        let mut result = Vec::with_capacity(tables.len());
        let table_names: Vec<&str> = tables.iter().map(|t| t.name.as_str()).collect();

        let rows = self
            .client
            .query(queries::SELECT_TABLES_EXISTS, &[&table_names])
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        rows.iter()
            .for_each(|row| result.push(row.get("table_name")));

        Ok(result)
    }

    fn generate_schema(&mut self, plan: &MigrationPlan) -> SqlzResult<()> {
        if !plan.is_valid() {
            return Err(SqlzError::MappingError(format!(
                "Invalid migration plan for table '{}'",
                plan.table.name
            )));
        }

        let mut sql = format!("CREATE TABLE public.{} (\n", plan.table.name);
        let mut column_defs = Vec::new();

        for col in &plan.table.columns {
            let type_str = plan.target_column_type_map.get(&col.name).unwrap();
            let mut def = format!("    {} {}", col.name, type_str);

            if let GenericType::Decimal { .. } = col.col_type {
                let precision = col.numeric_precision.unwrap();
                let scale = col.numeric_scale.unwrap();
                def.push_str(&format!("({},{})", precision, scale));
            } else if let Some(max_len) = col.max_length {
                def.push_str(&format!("({})", max_len));
            }

            if col.is_identity {
                def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
            }

            if !col.is_nullable {
                def.push_str(" NOT NULL");
            }

            // TODO: Set default value

            column_defs.push(def);
        }

        sql.push_str(&column_defs.join(",\n"));
        sql.push_str("\n);");

        self.client
            .batch_execute(&sql)
            .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

        Ok(())
    }

    fn migrate_data(&mut self, _plan: &MigrationPlan) -> SqlzResult<()> {
        todo!()
    }

    fn create_constraints(&mut self, _plan: &MigrationPlan) -> SqlzResult<()> {
        todo!()
    }

    fn read_rows(&self, table: &Table, options: RowReadOptions) -> Box<BatchQueryResult> {
        let mut sql = format!("SELECT * FROM {} ", table.name);

        let mut values = String::from("(");
        let mut keys = String::from("(");

        if let Some(pk) = &table.get_pk() {
            let total_columns = pk.columns.len();

            pk.columns.iter().enumerate().for_each(|(index, column)| {
                keys.push_str(&column.name);
                if let Some(cf) = &options.continue_from {
                    values.push_str(&format!("{}", cf.values[index]));
                }

                if index < total_columns - 1 {
                    keys.push_str(", ");
                    if options.continue_from.is_some() {
                        values.push_str(", ");
                    }
                }
            });
        } else {
            panic!("Table {} does not have a primary key", table.name);
        }

        keys.push(')');
        values.push(')');

        if options.continue_from.is_some() {
            sql.push_str(&format!("WHERE {keys} > {values} "));
        }

        sql.push_str(&format!("ORDER BY {keys} ASC"));
        sql.push_str(&format!(" LIMIT {}", options.batch_size));

        unimplemented!();
    }
}

fn read_table(client: &mut Client, table_name: String) -> SqlzResult<Table> {
    let mut table = Table {
        name: table_name,
        columns: Vec::new(),
        constraints: Vec::new(),
    };

    let column_rows = client
        .query(queries::SELECT_COLUMNS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in column_rows {
        let data_type: String = row.get("data_type");
        let udt_name: String = row.get("udt_name");
        let char_len: Option<i32> = row.get("character_maximum_length");
        let mut numeric_precision: Option<i32> = row.get("numeric_precision");
        let mut numeric_scale: Option<i32> = row.get("numeric_scale");

        let col_type = helper::map_native_type_to_sqlz(
            &data_type,
            &udt_name,
            char_len,
            numeric_precision,
            numeric_scale,
        );

        if !constants::PRECISION_TYPES.contains(&udt_name.as_str()) {
            numeric_precision = None;
            numeric_scale = None;
        }

        table.columns.push(Rc::new(Column {
            name: row.get("column_name"),
            is_nullable: row.get::<_, String>("is_nullable") == "YES",
            col_type,
            native_type: udt_name,
            is_identity: row.get::<_, String>("is_identity") == "YES",
            max_length: char_len,
            numeric_precision,
            numeric_scale,
        }));
    }

    Ok(table)
}

fn fill_constraints(client: &mut Client, table: &mut Table) -> SqlzResult<()> {
    let rows = client
        .query(queries::SELECT_CONSTRAINTS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in rows {
        let constraint_name: String = row.get("constraint_name");
        let constraint_type: String = row.get("constraint_type");
        let column_name: String = row.get("column_name");

        let column = table
            .columns
            .iter()
            .find(|c| c.name == column_name)
            .cloned();

        if let Some(col) = column {
            match constraint_type.as_str() {
                constants::CONSTRAINT_PK => {
                    // Check if we already have this PK (for multi-column PKs)
                    if let Some(ConstraintType::PrimaryKey(PrimaryKeyConstraint {
                        columns, ..
                    })) = table
                        .constraints
                        .iter_mut()
                        .find(|c| matches!(c, ConstraintType::PrimaryKey { .. }))
                    {
                        columns.push(col);
                    } else {
                        table
                            .constraints
                            .push(ConstraintType::PrimaryKey(PrimaryKeyConstraint {
                                constraint_name,
                                columns: vec![col],
                            }));
                    }
                }
                constants::CONSTRAINT_UNIQUE => {
                    // Group unique constraints by name
                    if let Some(ConstraintType::Unique { columns, .. }) =
                        table.constraints.iter_mut().find(|c| match c {
                            ConstraintType::Unique {
                                constraint_name: n, ..
                            } => n == &constraint_name,
                            _ => false,
                        })
                    {
                        columns.push(col);
                    } else {
                        table.constraints.push(ConstraintType::Unique {
                            constraint_name,
                            columns: vec![col],
                        });
                    }
                }
                _ => {}
            }
        }
    }

    Ok(())
}

fn fill_foreign_keys(
    client: &mut Client,
    table: &mut Table,
    column_lookup: &HashMap<(String, String), Rc<Column>>,
) -> SqlzResult<()> {
    let rows = client
        .query(queries::SELECT_FOREIGN_KEYS, &[&table.name])
        .map_err(|e| SqlzError::DatabaseError(Box::new(e)))?;

    for row in rows {
        let column_name: String = row.get("column_name");
        let foreign_table: String = row.get("foreign_table_name");
        let foreign_column: String = row.get("foreign_column_name");

        let source = table.columns.iter().find(|c| c.name == column_name);
        let target = column_lookup.get(&(foreign_table.clone(), foreign_column));

        if let (Some(src_col), Some(ref_col)) = (source, target) {
            table.constraints.push(ConstraintType::ForeignKey {
                constraint_name: row.get("constraint_name"),
                source_column: Rc::clone(src_col),
                referenced_table: foreign_table,
                referenced_column: Rc::clone(ref_col),
                on_update: helper::map_fk_action(&row.get::<_, String>("on_update")),
                on_delete: helper::map_fk_action(&row.get::<_, String>("on_delete")),
            });
        }
    }

    Ok(())
}
