use crate::sqlz::{GenericType, RowReadOptions, SqlzRow, SqlzValue, Table};
use std::collections::HashMap;
use crate::providers::postgresql::constants;

pub const SELECT_TABLES: &str = "\
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_schema NOT LIKE 'pg_%'
      AND table_schema <> 'information_schema'
      AND table_type = 'BASE TABLE';";

pub const SELECT_COLUMNS: &str = "\
    SELECT
        column_name,
        data_type,
        character_maximum_length,
        numeric_precision,
        numeric_scale,
        is_nullable,
        column_default,
        udt_name,
        is_identity
    FROM information_schema.columns
    WHERE table_name = $1
      AND table_schema = $2
    ORDER BY ordinal_position;";

pub const SELECT_CONSTRAINTS: &str = "\
    SELECT tc.constraint_name, tc.constraint_type, kcu.column_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_name = $1
      AND tc.table_schema = $2
      AND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE');";

pub const SELECT_FOREIGN_KEYS: &str = "\
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS foreign_table_schema,
        ccu.table_name AS foreign_table_name,
        ccu.column_name AS foreign_column_name,
        rc.update_rule AS on_update,
        rc.delete_rule AS on_delete
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.referential_constraints rc
        ON tc.constraint_name = rc.constraint_name
        AND tc.table_schema = rc.constraint_schema
    JOIN information_schema.constraint_column_usage ccu
        ON rc.unique_constraint_name = ccu.constraint_name
        AND rc.constraint_schema = ccu.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_name = $1
      AND tc.table_schema = $2
    ORDER BY tc.constraint_name, kcu.ordinal_position;";

pub const SELECT_TABLES_EXISTS: &str = "\
    SELECT table_name FROM information_schema.tables \
    WHERE table_schema = '{}' AND table_name = ANY($1);";

pub fn build_create_table_sql(
    table: &Table,
    target_column_type_map: HashMap<String, String>,
) -> String {
    let schema = table.schema.as_deref().unwrap_or_else(|| constants::SCHEMA_PUBLIC);
    let mut sql = format!("CREATE TABLE {}.{} (\n", schema, table.name);
    let mut column_defs = Vec::new();

    for col in &table.columns {
        let type_str = target_column_type_map.get(&col.name).unwrap();
        let mut def = format!("    {} {}", col.name, type_str);

        if let GenericType::Decimal { .. } = col.col_type {
            let precision = col.numeric_precision.unwrap();
            let scale = col.numeric_scale.unwrap();
            def.push_str(&format!("({},{})", precision, scale));
        } else if let Some(max_len) = col.max_length {
            def.push_str(&format!("({})", max_len));
        }

        if col.is_identity {
            def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if !col.is_nullable {
            def.push_str(" NOT NULL");
        }

        column_defs.push(def);
    }

    sql.push_str(&column_defs.join(",\n"));
    sql.push_str("\n);");
    sql
}

pub fn build_read_rows_sql(table: &Table, options: &RowReadOptions) -> (String, Vec<SqlzValue>) {
    let mut column_parts = Vec::new();
    for col in &table.columns {
        // Build columns list for SELECT
        match col.col_type {
            GenericType::UserDefined(_) => {
                // Force custom types to text so row.get::<String> works
                column_parts.push(format!("\"{}\"::TEXT as \"{}\"", col.name, col.name));
            }
            _ => {
                column_parts.push(format!("\"{}\"", col.name));
            }
        }
    }

    let mut sql = format!("SELECT {} FROM {} ", column_parts.join(", "), table.name);

    let mut values = String::from("(");
    let mut keys = String::from("(");
    let mut key_values = Vec::new();

    let pk = table.get_pk();
    if pk.is_none() {
        panic!("Table {} does not have a primary key", table.name);
    }
    let pk = pk.unwrap();

    let total_columns = pk.columns.len();

    pk.columns.iter().enumerate().for_each(|(index, column)| {
        keys.push_str(&column.name);
        if let Some(cf) = &options.continue_from {
            values.push_str(&format!("${}", index + 1));
            key_values.push(cf.where_params[index].clone());
        }

        if index < total_columns - 1 {
            keys.push_str(", ");
            if options.continue_from.is_some() {
                values.push_str(", ");
            }
        }
    });

    keys.push(')');
    values.push(')');

    if options.continue_from.is_some() {
        sql.push_str(&format!(" WHERE {keys} > {values} "));
    }

    sql.push_str(&format!("ORDER BY {keys} ASC"));
    sql.push_str(&format!(" LIMIT {}", options.batch_size));

    (sql, key_values)
}

pub fn build_write_rows_sql(table: &Table, rows: &Vec<SqlzRow>) -> (String, Vec<SqlzValue>) {
    if rows.is_empty() {
        return (String::new(), Vec::new());
    }

    let mut param_counter = 0;
    let mut params: Vec<SqlzValue> = Vec::new();
    let column_names: Vec<String> = table.columns.iter().map(|c| c.name.clone()).collect();
    let columns_str = column_names.join(", ");

    let mut values_placeholders = Vec::new();

    for row in rows {
        let mut row_placeholders = Vec::new();
        for col_name in &column_names {
            param_counter += 1;
            row_placeholders.push(format!("${}", param_counter));
            params.push(row.get(col_name).unwrap().clone());
        }
        values_placeholders.push(format!("({})", row_placeholders.join(", ")));
    }

    let sql = format!(
        "INSERT INTO {}.{} ({}) VALUES {}",
        table.schema.as_deref().unwrap_or_else(|| constants::SCHEMA_PUBLIC),
        table.name,
        columns_str,
        values_placeholders.join(", ")
    );

    (sql, params)
}
