use crate::sqlz::{
    GenericType, MigrationPlan, RowReadOptions, SqlzValue, Table,
};

pub const SELECT_TABLES: &str = "\
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE';";

pub const SELECT_COLUMNS: &str = "\
    SELECT
        column_name,
        data_type,
        character_maximum_length,
        numeric_precision,
        numeric_scale,
        is_nullable,
        column_default,
        udt_name,
        is_identity
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = $1
    ORDER BY ordinal_position;";

pub const SELECT_CONSTRAINTS: &str = "\
    SELECT tc.constraint_name, tc.constraint_type, kcu.column_name
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_schema = 'public'
      AND tc.table_name = $1
      AND tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE');";

pub const SELECT_FOREIGN_KEYS: &str = "\
    SELECT
        tc.constraint_name,
        kcu.column_name,
        ccu.table_schema AS foreign_table_schema,
        ccu.table_name AS foreign_table_name,
        ccu.column_name AS foreign_column_name,
        rc.update_rule AS on_update,
        rc.delete_rule AS on_delete
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    JOIN information_schema.referential_constraints rc
        ON tc.constraint_name = rc.constraint_name
        AND tc.table_schema = rc.constraint_schema
    JOIN information_schema.constraint_column_usage ccu
        ON rc.unique_constraint_name = ccu.constraint_name
        AND rc.constraint_schema = ccu.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_schema = 'public'
      AND tc.table_name = $1
    ORDER BY tc.constraint_name, kcu.ordinal_position;";

pub const SELECT_TABLES_EXISTS: &str = "\
    SELECT table_name FROM information_schema.tables \
    WHERE table_schema = 'public' AND table_name = ANY($1);";

pub fn build_create_table_sql(plan: &MigrationPlan) -> String {
    let mut sql = format!("CREATE TABLE public.{} (\n", plan.table.name);
    let mut column_defs = Vec::new();

    for col in &plan.table.columns {
        let type_str = plan.target_column_type_map.get(&col.name).unwrap();
        let mut def = format!("    {} {}", col.name, type_str);

        if let GenericType::Decimal { .. } = col.col_type {
            let precision = col.numeric_precision.unwrap();
            let scale = col.numeric_scale.unwrap();
            def.push_str(&format!("({},{})", precision, scale));
        } else if let Some(max_len) = col.max_length {
            def.push_str(&format!("({})", max_len));
        }

        if col.is_identity {
            def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if !col.is_nullable {
            def.push_str(" NOT NULL");
        }

        column_defs.push(def);
    }

    sql.push_str(&column_defs.join(",\n"));
    sql.push_str("\n);");
    sql
}

pub fn build_read_rows_sql(
    table: &Table,
    options: &RowReadOptions,
) -> (String, Vec<SqlzValue>) {
    let mut sql = format!("SELECT * FROM {} ", table.name);

    let mut values = String::from("(");
    let mut keys = String::from("(");
    let mut key_values = Vec::new();

    let pk = table.get_pk();
    if pk.is_none() {
        panic!("Table {} does not have a primary key", table.name);
    }
    let pk = pk.unwrap();

    let total_columns = pk.columns.len();

    pk.columns.iter().enumerate().for_each(|(index, column)| {
        keys.push_str(&column.name);
        if let Some(cf) = &options.continue_from {
            values.push_str(&format!("${}", index + 1));
            key_values.push(cf.where_params[index].clone());
        }

        if index < total_columns - 1 {
            keys.push_str(", ");
            if options.continue_from.is_some() {
                values.push_str(", ");
            }
        }
    });

    keys.push(')');
    values.push(')');

    if options.continue_from.is_some() {
        sql.push_str(&format!(" WHERE {keys} > {values} "));
    }

    sql.push_str(&format!("ORDER BY {keys} ASC"));
    sql.push_str(&format!(" LIMIT {}", options.batch_size));

    (sql, key_values)
}
